language: cpp

compiler:
  - gcc

os:
  - linux

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q

install:
  - sudo apt-get install -qq g++-4.9
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90

script:
    - cd tests
    - cmake .
    - make rsl_tests
    - ./rsl_tests
    
